### ISSUE TITLE
[Question] Powerwall Applicability

### ISSUE THREAD

**Issue by johnnyman727** [jsgoecke/tesla#20]
Hi @jsgoecke,

I was wondering if you have any insight into how adaptable this library could be for controlling a Tesla Powerwall. What would be the challenges with that endeavour?

**Comment by CWNE88** [comment]
What control are you looking to do with the Powerwall?

I've done monitoring but only via its own HTTP server, then doing the SNMP via a separate box.

Given that the setup and operation of it is done on client side javascript (about 42000 lines of it), you might be able to take that road and dig into the code.

**Comment by jnoxon** [comment]
The local API for the Tesla Energy Gateway is pretty well documented and not difficult to use, at least for data collection. That's the route I've taken. The advantage of getting it from the Tesla backend would be access to historical data, which is something I'd be interested in as well.

**Comment by johnnyman727** [comment]
Thanks for the feedback, everyone.
