### ISSUE TITLE
Login broken: HTTP 401

### ISSUE THREAD

**Issue by andig** [jsgoecke/tesla#38]
See https://github.com/andig/evcc/issues/624, https://tesla-api.timdorr.com/api-basics/authentication and https://github.com/timdorr/tesla-api/issues/215.

Will open PR once direction is clear. Input welcome.

**Comment by d4l3k** [comment]
@andig happy to review any PRs (not that I have merge permission))

**Comment by andig** [comment]
@jsgoecke would you consider giving merge permissions to parties interested in maintaining this library? A couple of people (like in this thread) are using this library and have found a couple of breakages that have remaining unfixed for some time.

/cc @bogosj

**Comment by andig** [comment]
We have meanwhile created a slightly more maintained fork at https://github.com/bogosj/tesla
